# Generated by Django 5.1.4 on 2024-12-23 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1, upload_to='EcomProject\\media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='added_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
