# Generated by Django 5.1.4 on 2024-12-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0004_category_remove_product_added_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
