# Generated by Django 5.1.4 on 2024-12-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0007_sub_category_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='indian', max_length=100),
        ),
    ]
