# Generated by Django 5.1.4 on 2024-12-30 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0010_alter_product_img_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 21, 17, 55, 609528)),
        ),
    ]
