# Generated by Django 5.1.4 on 2024-12-30 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0011_order_order_value_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 23, 21, 56, 76601)),
        ),
    ]
