# Generated by Django 5.1.4 on 2024-12-30 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0015_alter_order_date_alter_order_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 0, 43, 58, 692641)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('on_the_Way', 'on_the_Way')], default='pending', max_length=100),
        ),
    ]
